#!/usr/bin/env bash
# One-time server setup. Safe to re-run.
#
#   sudo ./scripts/setup-server.sh
#
# Prepares a Raspberry Pi or a fresh Linode identically: Docker, the
# /srv/lifeos layout, a generated .env, and Tailscale Serve in front of the
# loopback Nginx. Nothing here is specific to either host.
set -Eeuo pipefail

STATE_DIR="${LIFEOS_STATE_DIR:-/srv/lifeos}"
SERVICE_USER="${LIFEOS_DEPLOY_USER:-actions}"

say()  { printf '\033[1;34m▸\033[0m %s\n' "$*"; }
ok()   { printf '\033[32m✔\033[0m %s\n' "$*"; }
warn() { printf '\033[33m!\033[0m %s\n' "$*"; }
die()  { printf '\033[31m✘\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "run with sudo"
id "$SERVICE_USER" >/dev/null 2>&1 || die "deploy user '$SERVICE_USER' is missing; run nuniesmith/scripts generate-secrets.sh first"
SERVICE_GROUP="$(id -gn "$SERVICE_USER")"

say "Architecture: $(uname -m)"
case "$(uname -m)" in
    x86_64|aarch64|arm64) ok "supported" ;;
    # The published image is amd64 + arm64 only. A 32-bit Pi OS will pull an
    # image that cannot run, and the failure looks like a corrupt container.
    *) die "unsupported architecture $(uname -m); a 64-bit OS is required" ;;
esac

# ─── docker ────────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
    say "Installing Docker"
    curl -fsSL https://get.docker.com | sh
    ok "Docker installed"
else
    ok "Docker already present"
fi
docker compose version >/dev/null 2>&1 || die "docker compose plugin is missing"

if [[ -n "$SERVICE_USER" && "$SERVICE_USER" != "root" ]]; then
    # Not fatal. Docker's own installer normally creates this group, but if it
    # is missing, `set -e` would abort the whole setup here — before the state
    # directory and .env exist — and the failure would look like a problem
    # with those instead.
    getent group docker >/dev/null 2>&1 || groupadd docker 2>/dev/null || true
    if usermod -aG docker "$SERVICE_USER" 2>/dev/null; then
        ok "$SERVICE_USER added to the docker group (re-login to take effect)"
    else
        warn "could not add $SERVICE_USER to the docker group; deploys need it"
    fi
fi

# ─── layout ────────────────────────────────────────────────────────────────
say "Creating $STATE_DIR"
mkdir -p "$STATE_DIR"/{releases,backups,data/uploads,data/postgres}
# The SSH deployment account writes the lock, release history and backups.
chown "$SERVICE_USER:$SERVICE_GROUP" "$STATE_DIR" "$STATE_DIR/releases" "$STATE_DIR/backups"
chmod 750 "$STATE_DIR" "$STATE_DIR/releases" "$STATE_DIR/backups"
# The postgres image runs as uid 999; uploads are written by the app as node
# (uid 1000). Ownership is set explicitly rather than left to whoever writes
# first, which is how a container ends up unable to read its own volume.
chown -R 999:999 "$STATE_DIR/data/postgres"
chown -R 1000:1000 "$STATE_DIR/data/uploads"
chmod 700 "$STATE_DIR/data/postgres"
ok "layout created"

# ─── environment ───────────────────────────────────────────────────────────
ENV_FILE="$STATE_DIR/.env"
if [[ -f "$ENV_FILE" ]]; then
    ok ".env already exists; leaving it alone"
else
    say "Generating .env"
    POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 40)}"
    # A known first-login password, written here rather than only printed to
    # the container log. The log line scrolls away and rotates; this file is
    # already the host's secret store and is root/deploy-owned at 0600.
    # It stays a one-time credential: the account is created with
    # must_change_credentials, so signing in forces a real username and
    # password and revokes every other session.
    LIFEOS_BOOTSTRAP_PASSWORD="${LIFEOS_BOOTSTRAP_PASSWORD:-$(head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 24)}"
    HOSTNAME_TS="$(hostname)"
    cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-server.sh. Never copied from a CI runner.
NODE_ENV=production

# Set this to the Tailscale HTTPS name once \`tailscale serve\` is running.
ORIGIN=https://${HOSTNAME_TS}.ts.net

POSTGRES_DB=lifeos
POSTGRES_USER=lifeos_app
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://lifeos_app:${POSTGRES_PASSWORD}@db:5432/lifeos
MIGRATION_DATABASE_URL=postgresql://lifeos_app:${POSTGRES_PASSWORD}@db:5432/lifeos

# First-login password for the 'admin' account. Only used while no user
# exists; it is inert afterwards. Must be changed at first sign-in.
LIFEOS_BOOTSTRAP_PASSWORD=${LIFEOS_BOOTSTRAP_PASSWORD}

LIFEOS_TIMEZONE=America/Toronto
LIFEOS_CURRENCY=CAD

# Replaced by each deploy with the digest that was rolled out.
LIFEOS_IMAGE=
EOF
    ok ".env generated"
fi
# Also repair permissions from earlier setups without rotating credentials.
chown "$SERVICE_USER:$SERVICE_GROUP" "$ENV_FILE"
chmod 600 "$ENV_FILE"
ok ".env available to $SERVICE_USER (0600)"

# ─── tailscale ─────────────────────────────────────────────────────────────
if ! command -v tailscale >/dev/null 2>&1; then
    say "Installing Tailscale"
    curl -fsSL https://tailscale.com/install.sh | sh
    ok "Tailscale installed"
fi

if tailscale status >/dev/null 2>&1; then
    ok "Tailscale is connected as $(tailscale status --json | grep -o '"DNSName":"[^"]*"' | head -1 | cut -d'"' -f4)"
else
    warn "Tailscale is not connected. Run: sudo tailscale up"
fi

if grep -q '^LIFEOS_BOOTSTRAP_PASSWORD=.\+' "$ENV_FILE"; then
    say "First sign-in credentials"
    printf '    username: admin\n'
    printf '    password: %s\n' "$(grep '^LIFEOS_BOOTSTRAP_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)"
    printf '    You will be required to change both on first sign-in.\n'
fi

cat <<'NEXT'

Next steps
  1. sudo tailscale up                           (if not already connected)
  2. sudo tailscale serve --bg --https=443 8080  (HTTPS in front of loopback nginx)
  3. tailscale status                            (note the 100.x address)
  4. Put that address in the LIFEOS_TAILSCALE_IP repository secret
  5. Set ORIGIN in /srv/lifeos/.env to the https:// name tailscale serve printed
  6. Push to main — the deploy workflow takes it from there

Funnel must stay off. This host is reachable from the tailnet only.
NEXT
