import { createReadStream } from 'node:fs';
import { stat } from 'node:fs/promises';
import { isAbsolute, join, normalize, resolve, sep } from 'node:path';
import { Readable } from 'node:stream';
import { error } from '@sveltejs/kit';
import { env } from '$lib/server/env';
import { sql } from '$lib/server/db';
import { requireViewer } from '$lib/server/viewer';
import type { RequestHandler } from './$types';

/**
 * Serves an uploaded attachment.
 *
 * The import stores 207 images, records them in `attachments`, links them to
 * the records they came from, and carries them through export and restore. Up
 * to this route there was no way to look at any of them: every `<img>` in the
 * application pointed at a static asset bundled with the build, and nothing
 * served the upload directory. The whole media pipeline worked and ended
 * nowhere.
 *
 * Authorization is a household scope in SQL, not a filter in JavaScript, for
 * the same reason it is everywhere else here: a predicate that never runs
 * cannot be forgotten, and an id from a URL is exactly the input that finds a
 * missing one. Attachments carry `household_id` directly, so the check is the
 * lookup.
 */

const uploadRoot = resolve(env.LIFEOS_UPLOAD_DIR);

export const GET: RequestHandler = async ({ params, locals, setHeaders }) => {
	const viewer = await requireViewer(locals.user);

	const [row] = await sql<{ storage_key: string; content_type: string; byte_size: string }[]>`
		select storage_key, content_type, byte_size
		from attachments
		where id = ${params.id}::uuid
		  and household_id = ${viewer.householdId}::uuid
		  and archived_at is null
	`;

	// The same answer for "does not exist" and "belongs to another household":
	// a 403 would confirm the id is real, which is the one thing an id
	// enumerating attacker wants to learn.
	if (!row) error(404, 'Not found');

	// The storage key is generated by the importer, but it reaches this line
	// from the database and the database is restorable from a file, so it is
	// treated as untrusted: a key of `../../etc/passwd` must not escape the
	// upload directory.
	//
	// `isAbsolute` is belt-and-braces rather than a live path today — `join`
	// already treats an absolute second argument as a relative segment, so an
	// absolute key lands harmlessly inside the root. It is kept because the
	// obvious refactor of this line is `resolve`, where an absolute key WOULD
	// escape, and the guard should survive that edit.
	const candidate = normalize(join(uploadRoot, row.storage_key));
	if (isAbsolute(row.storage_key) || !candidate.startsWith(uploadRoot + sep)) {
		error(404, 'Not found');
	}

	let size: number;
	try {
		const info = await stat(candidate);
		if (!info.isFile()) error(404, 'Not found');
		size = info.size;
	} catch {
		// A row whose bytes are missing is a real condition — an import that
		// wrote its media somewhere else did exactly this — and it is a 404
		// rather than a 500 because the request is not what is broken.
		error(404, 'Not found');
	}

	setHeaders({
		'content-type': row.content_type,
		'content-length': String(size),
		// Content-addressed: the bytes at a given id never change, so this can
		// be cached hard. Private, because the response is household-scoped and
		// must not be held by a shared cache.
		'cache-control': 'private, max-age=31536000, immutable',
		'x-content-type-options': 'nosniff',
		// Uploaded bytes are served, so the browser must never be talked into
		// running them as a document.
		'content-security-policy': "default-src 'none'; img-src 'self'; style-src 'unsafe-inline'"
	});

	// Converted properly rather than cast. The first version of this passed the
	// Node stream straight to Response with `as unknown as ReadableStream`,
	// which serves the happy path perfectly and then kills the process the
	// first time a client goes away mid-image: undici tries to close a stream
	// that has already closed and throws ERR_INVALID_STATE outside any request,
	// where nothing can catch it. Closing a tab while a photo loaded was enough
	// to take the whole application down.
	//
	// `Readable.toWeb` produces a real web stream whose cancel destroys the
	// file handle, which is also what stops an abandoned download leaking a
	// descriptor.
	return new Response(Readable.toWeb(createReadStream(candidate)) as ReadableStream, {
		status: 200
	});
};
